# Generated by Django 5.2 on 2026-01-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='professions',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='service',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='services',
        ),
        migrations.AddField(
            model_name='listing',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent')], default='', max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold'), ('Rented', 'Rented')], default='', max_length=20),
        ),
    ]
