# Generated by Django 5.2 on 2026-01-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_listing_professions_remove_listing_room_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rooms',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5+')], default=0),
        ),
    ]
