# Generated by Django 5.2 on 2026-01-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_age_alter_listing_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='rooms',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
