# Generated by Django 5.2 on 2026-01-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='rooms',
            field=models.IntegerField(default=0),
        ),
    ]
